name: SPARQL Unicorn Ontology Documentation CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
    with:
      version: v017
      rdffilepath: thesaurus.ttl
      docpath: docs/
      prefixns: https://archaeolink.github.io/n4o-ta4-conservation/
      prefixnsshort: nfdi
      indexpages: true
      metadatatable: false
      createcollections: true
      createVOWL: true
      preferredlang: en
      ghpages: true
      ogcapifeatures: false
      iiif: false
      logourl: https://raw.githubusercontent.com/archaeolink/unicorn-ontdoc-template-n4o-ta4/main/icons/nfdi4objects_logo_bildmarke_digital_rund.png
      datasettitle: LEIZA Restaurierungs- und Konserverungsthesaurus
      templatedir: https://github.com/archaeolink/unicorn-ontdoc-template-n4o-ta4/archive/refs/tags/v0.2.zip
      publishingorg: <a href="http://leiza.de">Leibniz-Zentrum für Archäologie</a>
      publisher: Kristina Fella, Lasse Mempel-Lämnger, Florian Thiery
      license: CC BY 4.0
